# Generated by rust2rpm 24
%bcond_without check

%global crate gitjuggling

Name:           rust-gitjuggling
Version:        0.2.0
Release:        %autorelease
Summary:        Run a git command in all repositories under the current working directory

License:        MIT
URL:            https://crates.io/crates/gitjuggling
Source:         %{crates_source}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Run a git command in all repositories under the current working
directory.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%doc README.md
%{_bindir}/gitjuggling

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
